version: 2
jobs:
  build:
    working_directory: ~/likecoin-tx-poll
    docker:
      - image: node:14
    steps:
      - checkout
      # - restore_cache:
      #     key: likecoin-tx-poll-{{ .Environment.CACHE_UUID }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run:
          name: Dependencies
          command: npm install
      - run:
          name: Lint Test
          command: npm run lint
      # - save_cache:
      #     key: likecoin-tx-poll-{{ .Environment.CACHE_UUID }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      #     paths:
      #       - ./node_modules
